export interface Patient {
  id: string;
  name: string;
  age: number;
  condition: string;
  onset: string; // e.g. "6 months ago"
  affectedSide: "Left" | "Right" | "Bilateral";
  baselineMu: number;  // Mu power baseline (e.g. 15uV)
  activeMu: number;    // Mu power during intent attempt (suppressed, e.g. 4uV)
  baselineEMG: number; // Noise floor of EMG (e.g. 5uV)
  activeEMG: number;   // Muscle flexion target (e.g. 120uV)
  rehabGoal: string;
  notes: string;
}

export interface SNNConfig {
  threshold: number;       // V_th (mV)
  leak: number;            // leak fraction lambda (0 - 1)
  inputWeightEEG: number;  // Synaptic weight for EEG motor cortex channel (mV per spike)
  inputWeightEMG: number;  // Synaptic weight for EMG muscle channel (mV per spike)
  refractoryTicks: number; // Duration of refractory period (ticks)
  stdpRate: number;        // Learning rate for STDP (Spike-Timing-Dependent Plasticity)
  stdpEnabled: boolean;    // Is STDP active?
  deltaThresholdEEG: number; // Delta modulation threshold for EEG (uV)
  deltaThresholdEMG: number; // Delta modulation threshold for EMG (uV)
}

export interface SignalFrame {
  timestamp: number;
  eegValue: number;         // Raw EEG (amplitude in uV)
  emgValue: number;         // Raw EMG (amplitude in uV)
  eegSpike: boolean;        // Spike generated by EEG encoder
  emgSpike: boolean;        // Spike generated by EMG encoder
  membranePotential: number;// V_m of LIF neuron (mV)
  outputSpike: boolean;     // Spike output from LIF neuron (assistance triggered)
}

export interface SimulationMetrics {
  currentPowerUW: number;    // Power usage in microwatts (neuromorphic chips operate in microWatts!)
  currentLatencyMS: number;  // Latency in milliseconds (e.g. 1.2ms)
  firingRateEEG: number;     // Spike rate of EEG input (Hz)
  firingRateEMG: number;     // Spike rate of EMG input (Hz)
  snnSpikeCount: number;     // Number of final trigger spikes
  synapticEfficiency: number;// Multiplier indicating synapse adaptation
}

export interface CopilotMessage {
  id: string;
  sender: "user" | "copilot" | "system";
  text: string;
  timestamp: Date;
  status?: "sending" | "error" | "done";
}
